### PR TITLE
fixes related to windows filesystem specific

### LINKED ISSUE #53: Tests are failed on windows because file subsytem specific.
TestInisialize, TestInitialize_NumUnits_Decrease, TestInitialize_MutlipleFiles are failed. 

Fails are related to windows file system specific. Fix requires slightly rewrite file operations.

### PR DESCRIPTION
**Pull request by sudachen**
# Changes

There are three problems this PR fixes: 
*  NTFS when file is open exclusively, does not updated MFT on every operation. So when it lists directory it's not possible to get updated file size while file is open.
* Truncate operation requires GENERIC_WRITE permission, but when file is open with os.O_APPEND this permission is not requested on FileOpen. So it can't truncate  a windows file opened with os.O_APPEND flag.
* It can not remove a windows file until close it.

Closes #53

### CODE REVIEW

File: persistence/filewriter.go [hunk 1]
```diff
@@ -58,6 +59,8 @@ func (w *FileWriter) Truncate(numLabels uint64) error {
 	if err := w.file.Truncate(size); err != nil {
 		return fmt.Errorf("failed to truncate file: %v", err)
 	}
+	//w.file.Seek(0,os.SEEK_END)
```
Comment (moshababo) [inline persistence/filewriter.go]: Remove comment.

**Review by noamnelke — APPROVED** [review]
